filebeat.inputs:
  - type: filestream
    id: docker
    paths:
      - /var/lib/docker/containers/*/*.log
    parsers:
      - container: ~

processors:
  - add_docker_metadata: ~

  # Decode Spring Boot JSON inside the "message" field
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
      process_array: false
      max_depth: 4

  # Drop ELK self logs to avoid recursion
  - drop_event:
      when:
        or:
          - equals:
              container.name: "elasticsearch"
          - equals:
              container.name: "kibana"
          - equals:
              container.name: "logstash"
          - equals:
              container.name: "filebeat"

output.logstash:
  hosts: ["logstash:5044"]
